# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://liujinxia.github.io/
date_format: "ordinal"
title: MyNotes
subtitle: "nothing to say"
description: "刘晋霞的个人博客"
keywords: 刘晋霞
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
source_code: https://github.com/liujinxia/liujinxia.github.io/
side_bar_repo_limit: 5

version : 1

webrick:
  headers:
    Cache-Control: public, max-age=31536000

# ---------------- #
#      Author      #
# ---------------- #
author: 刘晋霞
organization: ThoughtWorks
organization_url: https://www.thoughtworks.com/
location: Beijing, China
email: liujinxia@hotmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /open-source/
    label: Open Source Projects

  -
    href: /about/
    label: 关于我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
highlighter: rouge
paginate: 9
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-gist
    # - jekyll-mentions that will breack https://search.google.com/structured-data/testing-tool
    - jekyll-seo-tag
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: liujinxia
facebook_username: liujinxia
weibo_username: liujinxia
zhihu_username: 刘晋霞
twitter_username: liujinxia

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面用户名为你自己申请的
disqus_username: liujinxia-github-io

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-82434482-1

baidu:
    analytics_id: 6148579727c35b751c976cb7e2694ed5

# ---------------- #
#      Datas       #
# ---------------- #
skill_language_keywords: [Java, Scala, Kotlin, Python, C Sharp]
skill_web_app_keywords: [TensorFlow, DeepLearning, Docker, Rancher, Ansible, javaEE, Spring, Spring MVC, JPA, Hibernate, MyBatis, Shiro, Redis, Spring Data,MySql]

theme: jekyll-theme-hacker